name: 'Library Checker Action'
description: 'This action runs yosupo06/library-checker-problems'
author: 'naminodarie'
inputs:
  command:
    required: true
    description: "Command for library checker\nIf you want skip a problem, exit before reading stdin."
  list-problems:
    required: true
    description: 'Command that lists the problems to check'
  repository-name:
    required: false
    description: 'library checcker repository'
    default: 'yosupo06/library-checker-problems'
  commit:
    required: false
    description: 'revision/branch/tag'
  cache-test-data:
    required: false
    default: 'false'
    description: 'If true, the action cache test datas'
# outputs:

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'rotate-cw'
  color: 'red'
runs:
  using: 'node12'
  main: 'dist/index.js'
