name: "Library Checker Action"
description: "This action runs yosupo06/library-checker-problems"
author: "naminodarie"
inputs:
  commit:
    required: false
    description: "revision/branch/tag"
    default: "HEAD"
# outputs: 

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'rotate-cw'
  color: 'red'
runs:
  using: "node12"
  main: "dist/index.js"
